version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: premialab/laravel-spark
    docker:
      - image: circleci/buildpack-deps:stretch
        auth:
          username: plabbot
          password: $DOCKERHUB_PASSWORD
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-tag:
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "plabbot" --password-stdin
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  test-build:
    jobs:
      - build:
          context:
            - docker
          filters:
            tags:
              only: /^test-v*/
            branches:
              ignore: /.*/
  build-master:
    jobs:
      - build:
          context:
            - docker
          filters:
            tags:
              only: /^v*/
            branches:
              ignore: /.*/
      - publish-tag:
          context:
            - docker
          requires:
            - build
          filters:
            tags:
              only: /^v*/
            branches:
              ignore: /.*/